# Generated by Django 2.2.3 on 2019-08-14 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatapeserta',
            name='lulus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biodatapeserta',
            name='skor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biodatapeserta',
            name='status',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodatapeserta',
            name='tanggalRegistrasi',
            field=models.DateField(default=datetime.datetime(2019, 8, 14, 7, 56, 42, 823090, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
