# Generated by Django 2.2.3 on 2019-08-14 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0022_accountprofile_flag'),
        ('peserta', '0002_auto_20190814_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSesi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kodeSesi', models.CharField(max_length=5)),
                ('tanggalBukaSesi', models.DateTimeField(auto_now_add=True)),
                ('jamMulai', models.DateTimeField()),
                ('jamSelesai', models.DateTimeField()),
                ('totalPeserta', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.AccountProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.SmallIntegerField(blank=True, null=True)),
                ('bobotPilihan', models.SmallIntegerField(blank=True, default=0)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.BiodataPeserta')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Sesi')),
            ],
        ),
    ]
