# Generated by Django 2.2.3 on 2019-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenDefault', models.PositiveIntegerField()),
                ('tanggalDiganti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
