# Generated by Django 2.2.3 on 2019-07-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_auto_20190725_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='foto',
            field=models.ImageField(default='company-profile-picture/default.png', upload_to='company-profile-picture'),
        ),
    ]
