# Generated by Django 2.2.3 on 2019-07-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_auto_20190725_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='alamatPerusahaan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='namaPerusahaan',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='noKontak',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
