# Generated by Django 2.2.3 on 2019-07-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_auto_20190725_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstatus',
            name='lastLogin',
        ),
    ]
