# Generated by Django 2.2.3 on 2019-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0009_rememberaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rememberaccount',
            name='timeLastSession',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
