# Generated by Django 2.2.3 on 2019-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0010_rememberaccount_timelastsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rememberaccount',
            name='timeLastSession',
            field=models.DateField(auto_now=True),
        ),
    ]
