# Generated by Django 2.2.3 on 2019-08-01 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0014_auto_20190801_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='tanggalRegistrasi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountprofile',
            name='jenisAkun',
            field=models.SmallIntegerField(choices=[(0, 'Demo'), (1, 'Premium')], default=0),
        ),
        migrations.DeleteModel(
            name='AccountStatus',
        ),
    ]
