# Generated by Django 2.2.3 on 2019-08-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0016_tokendefault'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenDefault',
        ),
    ]
