# Generated by Django 2.2.3 on 2019-08-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0019_accountprofile_npwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='idKecamatan',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='akun.Kecamatan'),
            preserve_default=False,
        ),
    ]
