# Generated by Django 2.2.3 on 2019-08-06 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0020_auto_20190806_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='idKecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.Kecamatan'),
        ),
    ]
